Repository SysoneEduTeam4/CheckMate, pull requests merged in 2024-08, with the labels that each got.

#49 [UI/admin/chartpage] UI 적용
  src/main/java/org/checkmate/admin/controller/view/ApplyStatusViewPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookCreatePageController.java
  src/main/java/org/checkmate/admin/controller/view/BookManagementPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusChartByDepartmentsPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusChartByTeamsPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookUpdatePageController.java
  src/main/java/org/checkmate/admin/controller/view/UserAddPageController.java
  src/main/java/org/checkmate/admin/util/FilePath.java
  src/main/resources/org/checkmate/view/layouts/admin/bookRentChartPageForDepartments.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookRentChartPageForTeams.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookUpdatePage.fxml
  src/main/resources/org/checkmate/view/style/admin/bookUpdatePage.css
Labels: ♻️ Refactor, 🎨 Design

#52 [Refactor/css/user] 사용자 도서신청 디자인 수정
  src/main/java/org/checkmate/user/controller/view/CreateBookRequestPageController.java
  src/main/java/org/checkmate/user/controller/view/MainPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadBookRequestPageController.java
  src/main/java/org/checkmate/user/util/FilePath.java
  src/main/resources/org/checkmate/icons/author.png
  src/main/resources/org/checkmate/icons/book.png
  src/main/resources/org/checkmate/icons/publisher.png
  src/main/resources/org/checkmate/view/layouts/user/createBookRequestPage.fxml
  src/main/resources/org/checkmate/view/layouts/user/readBookRequestPage.fxml
  src/main/resources/org/checkmate/view/style/user/createBookRequestPage.css
  src/main/resources/org/checkmate/view/style/user/readBookRequestPage.css
Labels: 🎨 Design

#55 :recycle: refactor : 차트 UI 리팩토링
  src/main/resources/org/checkmate/view/layouts/admin/bookRentChartPageForDepartments.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookRentChartPageForTeams.fxml
  src/main/resources/org/checkmate/view/style/admin/bookRentChartPageForPage.css
Labels: 🎁 FE, 🎨 Design

#56 :recycle: refactor : 로그인 예외 처리 기능 구현
  src/main/java/org/checkmate/admin/mapper/BookManagementMapper.java
  src/main/java/org/checkmate/common/controller/view/LoginPageController.java
  src/main/java/org/checkmate/common/service/LoginServiceImpl.java
  src/main/java/org/checkmate/user/mapper/MemberMapper.java
  src/main/resources/org/checkmate/sql/adminQuery.xml
  src/main/resources/org/checkmate/sql/userQuery.xml
Labels: ♻️ Refactor

#58 [Feat/user/book] 사용자 도서대여, 대여정보, 도서 신청 화면 및 기능 수정
  src/main/java/org/checkmate/user/controller/view/CreateBookRequestPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadBookRequestPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadLoanBookPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadLoanDoneBookPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadLoanNotReturnBookPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadOverdueBookPageController.java
  src/main/java/org/checkmate/user/mapper/BookMapper.java
  src/main/resources/org/checkmate/sql/userQuery.xml
  src/main/resources/org/checkmate/view/layouts/user/createBookRequestPage.fxml
  src/main/resources/org/checkmate/view/layouts/user/readBookRequestPage.fxml
  src/main/resources/org/checkmate/view/layouts/user/readLoanBookPage.fxml
  src/main/resources/org/checkmate/view/layouts/user/readLoanDoneBookPage.fxml
  src/main/resources/org/checkmate/view/layouts/user/readLoanNotReturnBookPage.fxml
  src/main/resources/org/checkmate/view/layouts/user/readOverdueBookPage.fxml
  src/main/resources/org/checkmate/view/style/user/readLoanBookPage.css
Labels: 🎉 BE, 🎁 FE, 🕋 DB

#59 [UI/Admin/BookCreate]
  src/main/java/org/checkmate/admin/controller/view/ApplyStatusViewPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookCreatePageController.java
  src/main/java/org/checkmate/admin/controller/view/BookManagementPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusChartByDepartmentsPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusChartByTeamsPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookUpdatePageController.java
  src/main/java/org/checkmate/admin/controller/view/UserAddPageController.java
  src/main/java/org/checkmate/admin/controller/view/UserManagementPageController.java
  src/main/java/org/checkmate/admin/mapper/UserManagementMapper.java
  src/main/java/org/checkmate/user/controller/view/CreateBookRequestPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadBookRequestPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadLoanDoneBookPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadLoanNotReturnBookPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadMyInformationPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadOverdueBookPageController.java
  src/main/java/org/checkmate/user/controller/view/TeamMemberLoanStatusPage.java
  src/main/java/org/checkmate/user/controller/view/UpdatePasswordPageController.java
  src/main/java/org/checkmate/user/util/FilePath.java
  src/main/resources/org/checkmate/icons/ISBN.png
  src/main/resources/org/checkmate/icons/book_cate.png
  src/main/resources/org/checkmate/icons/person.png
  src/main/resources/org/checkmate/view/layouts/admin/applyStatusViewPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookCreatePage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookManagementPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookRentChartPageForDepartments.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookRentChartPageForTeams.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookRentStatusPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookUpdatePage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/userAddPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/userManagementPage.fxml
  src/main/resources/org/checkmate/view/style/admin/bookCreatePage.css
  src/main/resources/org/checkmate/view/style/admin/bookManagementPage.css
  src/main/resources/org/checkmate/view/style/admin/bookRentChartPageForPage.css
  src/main/resources/org/checkmate/view/style/admin/bookUpdatePage.css
Labels: ✨ Feat, 🎁 FE, 🎨 Design

#57 [BE/Admin/Refactor] 관리자 admin 리팩토링 진행
  src/main/java/org/checkmate/admin/controller/server/BookController.java
  src/main/java/org/checkmate/admin/controller/view/BookManagementPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusChartByDepartmentsPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusChartByTeamsPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookUpdatePageController.java
  src/main/java/org/checkmate/admin/mapper/BookManagementMapper.java
  src/main/java/org/checkmate/admin/service/BookManagementService.java
  src/main/java/org/checkmate/admin/service/BookManagementServiceImpl.java
Labels: ♻️ Refactor, 🎉 BE

#60 [DB/USER/BOOK] 사용자 도서대여 목록 출력 쿼리 수정
  src/main/java/org/checkmate/admin/controller/server/BookController.java
  src/main/java/org/checkmate/admin/controller/view/ApplyStatusViewPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookCreatePageController.java
  src/main/java/org/checkmate/admin/controller/view/BookManagementPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusChartByDepartmentsPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusChartByTeamsPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookUpdatePageController.java
  src/main/java/org/checkmate/admin/controller/view/UserAddPageController.java
  src/main/java/org/checkmate/admin/controller/view/UserManagementPageController.java
  src/main/java/org/checkmate/admin/mapper/BookManagementMapper.java
  src/main/java/org/checkmate/admin/mapper/UserManagementMapper.java
  src/main/java/org/checkmate/admin/service/BookManagementService.java
  src/main/java/org/checkmate/admin/service/BookManagementServiceImpl.java
  src/main/java/org/checkmate/user/controller/view/CreateBookRequestPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadBookRequestPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadLoanDoneBookPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadLoanNotReturnBookPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadMyInformationPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadOverdueBookPageController.java
  src/main/java/org/checkmate/user/controller/view/TeamMemberLoanStatusPage.java
  src/main/java/org/checkmate/user/controller/view/UpdatePasswordPageController.java
  src/main/java/org/checkmate/user/util/FilePath.java
  src/main/resources/org/checkmate/sql/userQuery.xml
  src/main/resources/org/checkmate/view/layouts/admin/applyStatusViewPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookCreatePage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookManagementPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookRentChartPageForDepartments.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookRentChartPageForTeams.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookRentStatusPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookUpdatePage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/userAddPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/userManagementPage.fxml
  src/main/resources/org/checkmate/view/style/admin/bookManagementPage.css
  src/main/resources/org/checkmate/view/style/admin/bookRentChartPageForPage.css
  src/main/resources/org/checkmate/view/style/admin/bookUpdatePage.css
Labels: 🕋 DB

#61 [BE/Global/Test] 로그인 기능, 마이페이지 기능 서비스 테스트
  pom.xml
  src/main/java/org/checkmate/common/service/LoginService.java
  src/main/java/org/checkmate/common/service/LoginServiceImpl.java
  src/main/java/org/checkmate/user/mapper/BookMapper.java
  src/main/java/org/checkmate/user/service/BookServiceImpl.java
  src/test/java/org/checkmate/common/service/LoginServiceTest.java
Labels: ✨ Feat, 🏗️ Const, ✅ Test, 🎉 BE, 👷🏻 Build

#63 [BE/Global/Test] 사용자, 관리자 테스트 코드 작성 및 코드 리팩토링
  pom.xml
  src/main/java/module-info.java
  src/main/java/org/checkmate/common/controller/server/LoginController.java
  src/main/java/org/checkmate/common/controller/view/LoginPageController.java
  src/main/java/org/checkmate/common/dto/response/CommonResponse.java
  src/main/java/org/checkmate/common/service/LoginService.java
  src/main/java/org/checkmate/common/service/LoginServiceImpl.java
  src/main/java/org/checkmate/common/util/LoginSession.java
  src/main/java/org/checkmate/user/controller/server/BookController.java
  src/main/java/org/checkmate/user/controller/server/UserController.java
  src/main/java/org/checkmate/user/controller/view/TeamMemberLoanStatusPage.java
  src/main/java/org/checkmate/user/controller/view/UpdatePasswordPageController.java
  src/main/java/org/checkmate/user/dto/request/ReqLoginIdAndCurPasswordAndUpdatePassword.java
  src/main/java/org/checkmate/user/dto/response/UpdatePasswordResponseDto.java
  src/main/java/org/checkmate/user/mapper/BookMapper.java
  src/main/java/org/checkmate/user/mapper/MemberMapper.java
  src/main/java/org/checkmate/user/service/BookServiceImpl.java
  src/main/java/org/checkmate/user/service/MemberService.java
  src/main/java/org/checkmate/user/service/MemberServiceImpl.java
  src/main/resources/log4j2.properties
  src/test/java/org/checkmate/admin/AdminServiceTest.java
  src/test/java/org/checkmate/common/service/LoginServiceTest.java
  src/test/java/org/checkmate/user/MemberServiceTest.java
Labels: ♻️ Refactor, ✅ Test, 🎉 BE
