Repository SysoneEduTeam4/CheckMate, pull requests merged in 2024-07, with the labels that each got.

#5 [DB/Global/Build] JDBC Connection 환경 구성
  pom.xml
  src/main/java/module-info.java
  src/main/java/org/checkmate/database/DBConnector.java
  src/main/java/org/checkmate/database/SampleDataBaseConnection.java
Labels: 🌈 Global, 👷🏻 Build, 🕋 DB

#10 [BE/Global/Feat] 로그인 로직 개발
  pom.xml
  src/main/java/module-info.java
  src/main/java/org/checkmate/database/DBConnector.java
  src/main/java/org/checkmate/server/controller/LoginPageController.java
  src/main/java/org/checkmate/server/controller/SampleController.java
  src/main/java/org/checkmate/server/dto/request/LoginRequestDto.java
  src/main/java/org/checkmate/server/dto/request/SampleRequestDto.java
  src/main/java/org/checkmate/server/dto/response/LoginResponseDto.java
  src/main/java/org/checkmate/server/dto/response/SampleResponseDto.java
  src/main/java/org/checkmate/server/entity/MRole.java
  src/main/java/org/checkmate/server/entity/Member.java
  src/main/java/org/checkmate/server/entity/Sample.java
  src/main/java/org/checkmate/server/mapper/MemberMapper.java
  src/main/java/org/checkmate/server/mapper/SampleMapper.java
  src/main/java/org/checkmate/server/service/MemberService.java
  src/main/java/org/checkmate/server/service/MemberServiceImpl.java
  src/main/java/org/checkmate/server/service/Sample.java
  src/main/resources/org/checkmate/sql/Sample.sql
  src/main/resources/org/checkmate/sql/userQuery.xml
Labels: ✨ Feat, 🎉 BE, 🚨 HotFix, 🕋 DB

#12 [Be/feat/member] 로그인 로직(관리자, 유저), 비밀번호 암호화
  mvnw
  src/main/java/org/checkmate/server/controller/LoginPageController.java
  src/main/java/org/checkmate/server/dto/response/LoginResponseDto.java
  src/main/java/org/checkmate/server/entity/Member.java
  src/main/java/org/checkmate/server/service/MemberServiceImpl.java
  src/main/java/org/checkmate/server/util/PasswordEncoder.java
Labels: ✨ Feat, ♻️ Refactor, 🎉 BE, 🕋 DB

#14 [Fe/admin/feat] 관리자 메인페이지 view 개발
  pom.xml
  src/main/java/org/checkmate/server/controller/admin_MainController.java
  src/main/resources/org/checkmate/view/layouts/admin/mainPage.fxml
Labels: ✨ Feat, 🎁 FE, 👷🏻 Build

#15 [BE/Global/Feat] 사용자 세션 생성
  pom.xml
  src/main/java/module-info.java
  src/main/java/org/checkmate/server/controller/LoginPageController.java
  src/main/java/org/checkmate/server/controller/MainPageController.java
  src/main/java/org/checkmate/server/dto/request/LoginRequestDto.java
  src/main/java/org/checkmate/server/dto/response/LoginResponseDto.java
  src/main/java/org/checkmate/server/dto/response/MemberInfoResponseDto.java
  src/main/java/org/checkmate/server/entity/Member.java
  src/main/java/org/checkmate/server/mapper/MemberMapper.java
  src/main/java/org/checkmate/server/service/MemberService.java
  src/main/java/org/checkmate/server/service/MemberServiceImpl.java
  src/main/java/org/checkmate/server/util/MemberSession.java
  src/main/resources/org/checkmate/sql/userQuery.xml
  src/main/resources/org/checkmate/view/layouts/comm/loginPage.fxml
  src/main/resources/org/checkmate/view/style/login.css
Labels: ✨ Feat, ♻️ Refactor, 🎉 BE, 🌈 Global, 👷🏻 Build

#17 [DB/Users/feat] 사용자 sql 쿼리 문 개발
  src/main/resources/org/checkmate/icons/book.png
  src/main/resources/org/checkmate/icons/book1.png
  src/main/resources/org/checkmate/icons/books.jpg
  src/main/resources/org/checkmate/icons/user.png
  src/main/resources/org/checkmate/sql/userQuery.xml
Labels: 🕋 DB

#20 [ALL/Member/Feat] 비밀번호 변경 기능 추가
  pom.xml
  src/main/java/module-info.java
  src/main/java/org/checkmate/database/DBConnector.java
  src/main/java/org/checkmate/server/controller/changePwPageController.java
  src/main/java/org/checkmate/server/dto/request/ChangePwRequestDto.java
  src/main/java/org/checkmate/server/dto/response/ChangePwResponseDto.java
  src/main/java/org/checkmate/server/mapper/MemberMapper.java
  src/main/java/org/checkmate/server/service/MemberService.java
  src/main/java/org/checkmate/server/service/MemberServiceImpl.java
  src/main/resources/org/checkmate/sql/userQuery.xml
  src/main/resources/org/checkmate/view/layouts/user/changePwPage.fxml
Labels: ✨ Feat, ♻️ Refactor, 🎉 BE, 🎁 FE, 🍎 Chore, 🕋 DB

#21 [Docs/Hotfix/Member] : userQuery 내 필드 누락 핫픽스
  src/main/resources/org/checkmate/sql/userQuery.xml
Labels: 📝 Docs, 🚨 HotFix

#22 [ALL/Member/Feat] 마이페이지 기능 구현
  src/main/java/org/checkmate/server/controller/MyPageController.java
  src/main/java/org/checkmate/server/controller/changePwPageController.java
  src/main/java/org/checkmate/server/dto/response/MyPageResponsedto.java
  src/main/java/org/checkmate/server/mapper/MemberMapper.java
  src/main/java/org/checkmate/server/service/MemberService.java
  src/main/java/org/checkmate/server/service/MemberServiceImpl.java
  src/main/resources/org/checkmate/sql/userQuery.xml
  src/main/resources/org/checkmate/view/layouts/user/myPage.fxml
Labels: ✨ Feat, ♻️ Refactor, 🎉 BE, 🎁 FE

#26 [Feat/admin/book management] 관리자 도서관리 구현
  src/main/java/module-info.java
  src/main/java/org/checkmate/server/controller/MyPageController.java
  src/main/java/org/checkmate/server/controller/admin_bookAddController.java
  src/main/java/org/checkmate/server/controller/admin_bookManagementPageController.java
  src/main/java/org/checkmate/server/controller/admin_bookModifyController.java
  src/main/java/org/checkmate/server/dto/request/AddBookRequestDto.java
  src/main/java/org/checkmate/server/dto/request/EditBookRequestDto.java
  src/main/java/org/checkmate/server/dto/response/AddBookResponseDto.java
  src/main/java/org/checkmate/server/dto/response/ChangePwResponseDto.java
  src/main/java/org/checkmate/server/dto/response/EditBookResponseDto.java
  src/main/java/org/checkmate/server/dto/response/FindAllBooksAdminResponseDto.java
  src/main/java/org/checkmate/server/dto/response/FindSelectedBookAdminResponseDto.java
  src/main/java/org/checkmate/server/entity/BookLoanStatus.java
  src/main/java/org/checkmate/server/mapper/BookMapper.java
  src/main/java/org/checkmate/server/mapper/MemberMapper.java
  src/main/java/org/checkmate/server/service/BookService.java
  src/main/java/org/checkmate/server/service/BookServiceImpl.java
  src/main/java/org/checkmate/server/util/StringSplit.java
  src/main/java/org/checkmate/server/util/TypeFormatter.java
  src/main/resources/org/checkmate/sql/adminQuery.xml
  src/main/resources/org/checkmate/sql/userQuery.xml
  src/main/resources/org/checkmate/view/layouts/admin/bookAddPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookManagementPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookModifyPage.fxml
Labels: ✨ Feat, ♻️ Refactor, 🎉 BE, 🎁 FE, 🕋 DB

#25 [ALL/Admin/Feat, Fix] 관리자 사용자 조회 기능 개발 및 쿼리문 수정
  src/main/java/org/checkmate/server/controller/adminUserPageController.java
  src/main/java/org/checkmate/server/dto/response/AdminMemberResponseDto.java
  src/main/java/org/checkmate/server/entity/AdminMember.java
  src/main/java/org/checkmate/server/mapper/AdminMemberMapper.java
  src/main/java/org/checkmate/server/service/AdminMemberService.java
  src/main/resources/org/checkmate/sql/adminQuery.xml
  src/main/resources/org/checkmate/sql/userQuery.xml
  src/main/resources/org/checkmate/view/layouts/admin/userPage.fxml
Labels: ✨ Feat, 🎉 BE, 🎁 FE

#30 [DB/Global/Fix] sql 쿼리 문 수정
  src/main/resources/org/checkmate/sql/adminQuery.xml
  src/main/resources/org/checkmate/sql/userQuery.xml
Labels: 🔨 Fix, 🕋 DB

#32 [Feat/user/book] 사용자 도서대여 구현
  src/main/java/org/checkmate/user/controller/server/BookController.java
  src/main/java/org/checkmate/user/controller/view/MainPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadLoanBookPageController.java
  src/main/java/org/checkmate/user/dto/request/CreateBookLoanRequestDto.java
  src/main/java/org/checkmate/user/dto/request/ReadSearchLoanStatusRequestDto.java
  src/main/java/org/checkmate/user/dto/response/CreateBookLoanResponseDto.java
  src/main/java/org/checkmate/user/dto/response/ReadLoanStatusResponseDto.java
  src/main/java/org/checkmate/user/dto/response/ReadSearchLoanStatusResponseDto.java
  src/main/java/org/checkmate/user/mapper/BookMapper.java
  src/main/java/org/checkmate/user/service/BookService.java
  src/main/java/org/checkmate/user/service/BookServiceImpl.java
  src/main/resources/org/checkmate/icons/search.png
  src/main/resources/org/checkmate/sql/userQuery.xml
  src/main/resources/org/checkmate/view/layouts/user/readLoanBookPage.fxml
Labels: ✨ Feat, ♻️ Refactor, 🎉 BE, 🎁 FE, 🕋 DB

#33 [Refactor/Admin/Book management] 도서 관리 검색 기능 추가 및 리팩토링 진행
  src/main/java/org/checkmate/admin/controller/server/BookController.java
  src/main/java/org/checkmate/admin/controller/view/BookManagementPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookUpdatePageController.java
  src/main/java/org/checkmate/admin/controller/view/ManagementPageController.java
  src/main/java/org/checkmate/admin/controller/view/UserManagementPageController.java
  src/main/java/org/checkmate/admin/dto/request/BookUpdateRequestDto.java
  src/main/java/org/checkmate/admin/mapper/BookManagementMapper.java
  src/main/java/org/checkmate/admin/service/BookManagementService.java
  src/main/java/org/checkmate/admin/service/BookManagementServiceImpl.java
  src/main/resources/org/checkmate/sql/adminQuery.xml
  src/main/resources/org/checkmate/view/layouts/admin/bookManagementPage.fxml
Labels: ✨ Feat, ♻️ Refactor, 🎉 BE, 🎁 FE, 🕋 DB

#38 [Feat/be/admin] 사용자 검색 기능 , 비밀번호 초기화 기능 추가
  src/main/java/org/checkmate/admin/controller/view/UserAddPageController.java
  src/main/java/org/checkmate/admin/controller/view/UserManagementPageController.java
  src/main/java/org/checkmate/admin/dto/response/AdminMemberResponseDto.java
  src/main/java/org/checkmate/admin/mapper/UserManagementMapper.java
  src/main/java/org/checkmate/admin/service/MemberService.java
  src/main/java/org/checkmate/admin/service/MemberServiceImpl.java
  src/main/resources/org/checkmate/sql/adminQuery.xml
  src/main/resources/org/checkmate/view/layouts/admin/userManagementPage.fxml
Labels: ✨ Feat, 🎉 BE

#36 [BE/User/Feat] 나의 팀원 대여 현황 조회 기능 개발
  src/main/java/org/checkmate/common/exception/DatabaseException.java
  src/main/java/org/checkmate/user/controller/server/BookController.java
  src/main/java/org/checkmate/user/dto/request/ReqLoginIdAndTeamId.java
  src/main/java/org/checkmate/user/dto/response/TeamMemberLoanStatusDegree.java
  src/main/java/org/checkmate/user/dto/response/TeamMemberLoanStatusForView.java
  src/main/java/org/checkmate/user/mapper/BookMapper.java
  src/main/java/org/checkmate/user/service/BookService.java
  src/main/java/org/checkmate/user/service/BookServiceImpl.java
  src/main/resources/org/checkmate/sql/userQuery.xml
  src/main/resources/org/checkmate/view/style/user/readMyInformationPage.css
Labels: ✨ Feat, ♻️ Refactor, 🏷️ Comment, 🎉 BE

#40 [ Design/All ] 모든 페이지에 사이드바 적용 , 프로그램 종료 버튼 적용 , 사이즈 통일
  src/main/java/org/checkmate/admin/controller/view/ApplyStatusViewPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookCreatePageController.java
  src/main/java/org/checkmate/admin/controller/view/BookManagementPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookUpdatePageController.java
  src/main/java/org/checkmate/admin/controller/view/UserAddPageController.java
  src/main/java/org/checkmate/admin/controller/view/UserManagementPageController.java
  src/main/java/org/checkmate/admin/mapper/UserManagementMapper.java
  src/main/java/org/checkmate/user/controller/view/ReadLoanBookPageController.java
  src/main/java/org/checkmate/user/controller/view/ReadMyInformationPageController.java
  src/main/java/org/checkmate/user/controller/view/UpdatePasswordPageController.java
  src/main/resources/org/checkmate/view/layouts/admin/applyStatusViewPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookCreatePage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookManagementPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookUpdatePage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/userAddPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/userManagementPage.fxml
  src/main/resources/org/checkmate/view/layouts/user/readLoanBookPage.fxml
  src/main/resources/org/checkmate/view/layouts/user/readMyInformationPage.fxml
  src/main/resources/org/checkmate/view/layouts/user/updatePasswordPage.fxml
Labels: 🎨 Design

#41 [Feat/Admin/book rent status] 대여현황 기능 개발
  src/main/java/org/checkmate/admin/controller/server/BookController.java
  src/main/java/org/checkmate/admin/controller/view/BookManagementPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusChartByDepartmentsPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusChartByTeamsPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusPageController.java
  src/main/java/org/checkmate/admin/controller/view/ManagementPageController.java
  src/main/java/org/checkmate/admin/dto/response/ReadBookLoanRecordsForChartResponseDto.java
  src/main/java/org/checkmate/admin/dto/response/ReadBookLoanRecordsResponseDto.java
  src/main/java/org/checkmate/admin/mapper/BookManagementMapper.java
  src/main/java/org/checkmate/admin/service/BookManagementService.java
  src/main/java/org/checkmate/admin/service/BookManagementServiceImpl.java
  src/main/java/org/checkmate/admin/util/FilePath.java
  src/main/java/org/checkmate/common/util/Departments.java
  src/main/java/org/checkmate/common/util/Teams.java
  src/main/resources/org/checkmate/sql/adminQuery.xml
  src/main/resources/org/checkmate/view/layouts/admin/bookManagementPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookRentChartPageForDepartments.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookRentChartPageForTeams.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookRentStatusPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookUpdatePage.fxml
  src/main/resources/org/checkmate/view/layouts/user/updatePasswordPage.fxml
Labels: ✨ Feat, ♻️ Refactor, 🔨 Fix, 🎉 BE, 🎁 FE, 🕋 DB

#43 [FE/Global/Design] 화면 템플릿 구성
  src/main/java/org/checkmate/user/controller/view/TemplatePage.java
  src/main/resources/org/checkmate/icons/book.png
  src/main/resources/org/checkmate/icons/books.jpg
  src/main/resources/org/checkmate/icons/side_menu_bu.png
  src/main/resources/org/checkmate/view/layouts/user/templatePage.fxml
  src/main/resources/org/checkmate/view/style/user/templatePage.css
Labels: 🎁 FE, 🌈 Global, 🎨 Design

#45 [refactor/css/admin] : 사원 관리 페이지에 사이드바 적용
  src/main/java/org/checkmate/admin/controller/view/UserManagementPageController.java
  src/main/resources/org/checkmate/view/layouts/admin/userManagementPage.fxml
  src/main/resources/org/checkmate/view/layouts/user/templatePage.fxml
Labels: ♻️ Refactor, 🎨 Design

#46 [Refactor/user/changepw] 유저 비밀번호 변경 기능 리팩토링
  src/main/java/org/checkmate/admin/controller/server/BookController.java
  src/main/java/org/checkmate/admin/controller/view/BookCreatePageController.java
  src/main/java/org/checkmate/admin/controller/view/BookManagementPageController.java
  src/main/java/org/checkmate/admin/mapper/BookManagementMapper.java
  src/main/java/org/checkmate/admin/service/BookManagementService.java
  src/main/java/org/checkmate/admin/service/BookManagementServiceImpl.java
  src/main/java/org/checkmate/common/service/LoginServiceImpl.java
  src/main/java/org/checkmate/user/controller/view/UpdatePasswordPageController.java
  src/main/java/org/checkmate/user/dto/request/UpdatePasswordRequestDto.java
  src/main/java/org/checkmate/user/mapper/MemberMapper.java
  src/main/java/org/checkmate/user/util/FilePath.java
  src/main/resources/org/checkmate/sql/userQuery.xml
  src/main/resources/org/checkmate/view/layouts/user/updatePasswordPage.fxml
Labels: ✨ Feat, ♻️ Refactor, 🎉 BE, 🕋 DB

#47 [Refactor/css/admin] 디자인 변경
  src/main/java/org/checkmate/admin/controller/view/ApplyStatusViewPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookManagementPageController.java
  src/main/java/org/checkmate/admin/controller/view/BookRentStatusPageController.java
  src/main/java/org/checkmate/admin/controller/view/UserAddPageController.java
  src/main/java/org/checkmate/admin/controller/view/UserManagementPageController.java
  src/main/resources/org/checkmate/icons/name.png
  src/main/resources/org/checkmate/view/layouts/admin/applyStatusViewPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookManagementPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/bookRentStatusPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/userAddPage.fxml
  src/main/resources/org/checkmate/view/layouts/admin/userManagementPage.fxml
  src/main/resources/org/checkmate/view/style/admin/userAddPage.css
Labels: 🎨 Design
